### ISSUE TITLE
mod pack permission query 

### ISSUE THREAD

**Issue by mrgreaper** [clienthax/chococraft#10]
I looked around for a license and found this

Modpacks:
[spoiler]Since I have been asked a few times for permission to add my mod to a mod-pack, here my general terms. If they are meet, you can send me a message asking for permission. If they are not meet, dont bother ...

- no money will be made from the download of the mod-pack (URL-shortener, click-counter etc...)
- Link to the ChocoCraft OP on www.minecraftforum.net will be provided in a text file included with the mod-pack (text file of mods list is sufficient)
- Link to the ChocoCraft OP will be provided on your community/server web page if available
- Modpack users will be informed about the latest version of ChocoCraft, thus I don't want to hear every to often about bugs fixed in the current official version, but not in the pack version.
- I can revoke my permission any time (which I don't intend to do unprovoked without the modpacker doing anything objectionable)

https://github.com/clienthax/chococraft/blob/master/MinecraftForumOP.txt

however the forum post seems to be the previous owner of the mod, and has not been active on the forum since september, plus it is your version of the mod we would like to use (we are after all in 1.7.10) so it makes sense to get your permission

assuming you have the same policy i shall continue,
MY mod pack is a ftb open pack ( http://forum.feed-the-beast.com/threads/1-7-10-craft-modpack-tech-magic-casual-server-files.58507/ )

as a feed the beast pack, all downloading etc is delt with on thier client side, there is no money made on my side (its not why i have created the mod pack, i have done it to share what i feel are good mods that make a good game when shared together)

thier is already a mod.txt file in the format of mod name , link to mod (in this case the github would be the link ? the minecraft forum post seems to be the old author)... author name 

The modpack at the moment is updated often so it will usually be the most recent version of the mod that is in the pack (there is usually a delay while i test mods make sure thier compatable, that is in fact what im doing with chococraft at the moment.

You are ofcourse free to revoke permission at anytime, though i dont see us violating any of the other rules

As part of the rules all mods that are not on feed the beasts open policy list (or are on thier as notify or request http://forum.feed-the-beast.com/threads/permissions-spreadsheet.50035/ ) have to have proof of permission before being added to the public packs, will you grant us that permission to use your mod? 

(again sorry this is a github issue post and not a pm, but no pm ability in github)

**Comment by clienthax** [comment]
the new forum post still has that clause so its fine ;)

**Comment by mrgreaper** [comment]
cool thank you, will be a few days before it appears in the public pack (got a fair few new mods were securing persons on and testing compatability with :) if you want a specific link added in the text file for the mod, just post it here and ill make sure it is that one (not seen the new forum post, can only find the old one, but work internet is sloooow )

**Comment by clienthax** [comment]
this is the link to the new one,
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2269183-clienthaxs-chococraft-happiness-distilled-into

**Comment by mrgreaper** [comment]
will add that to the mod list text file.
