### ISSUE TITLE
4.1.5 Chocobos go berserk with Pack bag 

### ISSUE THREAD

**Issue by CurePindal** [clienthax/chococraft#13]
Hey Client!

I noticed that Chocobos go berserk when you attach a pack bag and leash them to a fence. They constantly sprint around in circles!
Can you fix that please?

**Comment by clienthax** [comment]
Welp, thats amusing xD,
time to fixy

**Comment by clienthax** [comment]
Ok, issue was the follow ai triguring when you place the bag onto the chocobo, and the ai task not checking for leashing
