### ISSUE TITLE
Chocobo spawns replaced by models from other mods

### ISSUE THREAD

**Issue by CurePindal** [clienthax/chococraft#16]
There seems to be a weird issue where chocobo spawns are replaced by entity models from other mods. 
This is confirmed for Necromancy (Isaac Body) and Atum mod (mummies):

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2269183-clienthaxs-chococraft-happiness-distilled-into?page=10#c186

**Comment by clienthax** [comment]
@AtomicStryker any idea on this?

**Comment by AtomicStryker** [comment]
No clue, i don't really know how rendering is done internally other than how to register my models.

**Comment by LemADEC** [comment]
Did we check for overlapping entityIds in the configuration?

**Comment by clienthax** [comment]
@LemADEC i believe its because chococraft used global ids, something that has been fixed in the rewrite.
