### ISSUE TITLE
Strange Straw Generation

### ISSUE THREAD

**Issue by DefaltRat** [clienthax/chococraft#19]
Straw generated in caves like an ore. This is strange lookin. I think, this is a bug. I tested 4.1.5 version of ChocoCraft on Biomes'O'Plenty mod and vanila World Generation. It has the same result. Also, Gysahl spawned in superflat world mode.

![2015-07-18_00 56 39](https://cloud.githubusercontent.com/assets/13387545/8758736/b8787016-2cf8-11e5-9599-f9d1d6b504f4.png)
![2015-07-18_00 07 04](https://cloud.githubusercontent.com/assets/13387545/8758738/b87c0136-2cf8-11e5-994f-3de6ea2b087f.png)
![2015-07-18_00 07 14](https://cloud.githubusercontent.com/assets/13387545/8758737/b87bc680-2cf8-11e5-8ffb-a57ec6ad6ae9.png)
![2015-07-18_00 18 18](https://cloud.githubusercontent.com/assets/13387545/8758739/b87c6b44-2cf8-11e5-87bf-660dcc8a300f.png)
![2015-07-18_00 18 47](https://cloud.githubusercontent.com/assets/13387545/8758741/b87f733e-2cf8-11e5-85a1-d82e91869501.png)
![2015-07-18_00 19 05](https://cloud.githubusercontent.com/assets/13387545/8758740/b87f2488-2cf8-11e5-8706-1c37e0df02d9.png)
![2015-07-18_00 19 15](https://cloud.githubusercontent.com/assets/13387545/8758742/b896d736-2cf8-11e5-9de4-f4ce2b4de5a0.png)

**Comment by DefaltRat** [comment]
PROBLEM SOLVED!
Reason: ChocoCraft conflicted with ClashsoftLib (ClashsoftHUD mod).
Deleting this mod solved the problem of generation Straw everywhere. xD
Problem with generation Gysahl in superfalt world still remained.

**Comment by clienthax** [comment]
Heh, thats a very odd bug, i wonder what they did to cause it lol

**Comment by DefaltRat** [comment]
I think that this problem clashsoft lib in that it recognizes certain block as ore, the ore that are not, and adds the block to the generation of the world. I tested a little bit your mod with this library and found not only the straw but like a sponge and in mines . So the problem is not in your mod. Generally clashsoft lib is sooo weird mod. Thank you for your mod! It is very wonderful !
Issue closed.
