### ISSUE TITLE
Invisible Chocobos 

### ISSUE THREAD

**Issue by grapedragon** [clienthax/chococraft#20]
I have been playing a mix of mods including Chococraft and I can't see Chocobos. I can hear them, I can see them drop feathers and I have restarted and still can't see them. 
i have been playing with the following mods:
lucky blocks
iron chest
journey map
not enough items
orespawn
pam's harvestcraft
pandora box
storage drawers
tinker's
waila

**Comment by sweetsosweet** [comment]
Hello, I'd like to add that I'm also having this issue. Between the two of us, the mods we have in common are:
iron chest
journey map
not enough items
storage drawers
waila

but I have many more mods in addition.

In my fml-log when I tried to spawn Chocobo, I got this message:
[19:56:05] [Client thread/INFO] [FML/]: Server attempted to spawn an unknown entity using ID: {0} at ({1}, {2}, {3}) Skipping!
[19:56:05] [Client thread/DEBUG] [FML/]: Attempted to adjust the position of entity 13015 which is not present on the client

Like grapedragon, my Chocobo make sounds and drop feathers but are completely invisible.
