### ISSUE TITLE
Mod not loading on Cauldron 198 server

### ISSUE THREAD

**Issue by BigDrewskii** [clienthax/chococraft#9]
http://pastebin.com/pE26JYvX

**Comment by mrgreaper** [comment]
were using it on a normal server and the only issue we have is a crash when right click the chocobo with the second gysahl green (and its a client side only crash, when the player logs back in the bird is tammed)

**Comment by clienthax** [comment]
@mrgreaper open a seperate issue for that please.

**Comment by clienthax** [comment]
@BigDrewskii @OnslaughtFei Im unable to get cauldron to actually work (aparantly some librarys were pulled), can you email me a barebones server folder?, clienthax@gmail.com

**Comment by mrgreaper** [comment]
@clienthax can do, just need the time to get any logs etc (was more posting to say that it does indeed work on a forge server, just the minor annoyance bug, rather then a full on heres a bug help help help  if that makes sense :) ) 
i do know your mod has cheered up a friend of mine no end

**Comment by BigDrewskii** [comment]
It has been fixed with the 1235 cauldron build! All is good =]
